work_dir: ~/work/asllvd-skeleton/dataset
debug: False
mode: 3d
fps_out: 3
phases: 
  download, 
  segment, 
  skeleton,
  normalize

metadata:
  path:  ~/work/asllvd-skeleton/dataset/dai-asllvd.xlsx
  download_url: http://www.bu.edu/asllrp/dai-asllvd-BU_glossing_with_variations_HS_information-extended-urls-RU.xlsx

download:
  delete_on_finish: True
  output_dir: ./download
  url: http://csr.bu.edu/ftp/asl/asllvd/asl-data2/quicktime/{session}/scene{scene}-camera{camera}.mov

segment:
  delete_on_finish: True
  input_dir: ../original
  output_dir: ./segmented
  vidreader_path: ./3rd_party/windows/vidReader.exe
  fps_in: 60

skeleton:
  delete_on_finish: False
  input_dir: ./segmented
  output_dir: ./skeleton
  openpose_path: openpose
  models_dir: /openpose/models

normalize:
  delete_on_finish: False
  input_dir: ./skeleton
  output_dir: ./normalized
